"""
mock_data.py

Demo dataset: 6 mentors (total capacity 22) and 20 mentees
designed to produce clear, high-confidence matches.

Mentor → expected mentee group assignments:
  Dr. Ana Reyes      (ML / AI)             ← Group Prometheus, Neural Architects, Data Forge, Algorithm X
  Prof. Ben Santos   (Software / Web)      ← Code Collective, DevStack, WebForge, System Builders
  Dr. Clara Mendoza  (Cybersecurity)       ← CipherForce, SecureGuard, NetShield
  Prof. David Lim    (Database / Big Data) ← DataVault, QueryPros, SchemaBuilders
  Dr. Elena Cruz     (Computer Vision)     ← VisionLab, PixelMinds, SightTech
  Prof. Felix Tan    (Mobile / IoT)        ← MobileHub, IoTLink, EmbedDev
"""

MOCK_MENTORS = [
    {
        "id":                    "a0000000-0000-0000-0000-000000000001",
        "first_name":            "Ana",
        "last_name":             "Reyes",
        "email":                 "ana.reyes@demo.edu",
        "technical_skills":      ["Python", "TensorFlow", "scikit-learn", "deep learning", "neural networks", "machine learning"],
        "forte":                 ["machine learning", "artificial intelligence", "data science", "neural networks"],
        "available_days":        ["Monday", "Wednesday", "Friday"],
        "time_slot":             ["morning", "afternoon"],
        "communication_preference": "hybrid",
        "meeting_frequency":     "weekly",
        "experience":            8,
        "mentor_capacity":       4,
        "prior_mentees_count":   6,
        "self_description":      "I specialize in machine learning and deep learning, with research in neural network architectures and AI-driven data science applications.",
        "prev_mentored_thesis":  [
            "Machine Learning for Predictive Student Analytics",
            "Deep Learning Approaches to Medical Imaging",
        ],
        "published_papers":      [
            "Transfer Learning in Healthcare Diagnosis using TensorFlow",
            "Scikit-learn Pipelines for Large-scale Machine Learning",
        ],
        "certifications":        ["TensorFlow Developer Certificate", "AWS Machine Learning Specialty"],
        "profile_completed":     True,
    },
    {
        "id":                    "a0000000-0000-0000-0000-000000000002",
        "first_name":            "Ben",
        "last_name":             "Santos",
        "email":                 "ben.santos@demo.edu",
        "technical_skills":      ["JavaScript", "React", "Node.js", "TypeScript", "software architecture", "agile"],
        "forte":                 ["web development", "software engineering", "full-stack development", "agile methodology"],
        "available_days":        ["Tuesday", "Thursday", "Friday"],
        "time_slot":             ["afternoon", "evening"],
        "communication_preference": "online",
        "meeting_frequency":     "biweekly",
        "experience":            6,
        "mentor_capacity":       4,
        "prior_mentees_count":   5,
        "self_description":      "I focus on software engineering and full-stack web development using React, Node.js, and TypeScript with agile practices.",
        "prev_mentored_thesis":  [
            "Agile Software Development for SMEs",
            "Full-stack Web Application for Campus Events",
        ],
        "published_papers":      [
            "Component-Driven Architecture in React Applications",
            "Node.js Scalability Patterns for REST APIs",
        ],
        "certifications":        ["AWS Certified Developer", "Scrum Master Certified"],
        "profile_completed":     True,
    },
    {
        "id":                    "a0000000-0000-0000-0000-000000000003",
        "first_name":            "Clara",
        "last_name":             "Mendoza",
        "email":                 "clara.mendoza@demo.edu",
        "technical_skills":      ["penetration testing", "network security", "cryptography", "Python", "Linux", "Kali Linux", "ethical hacking"],
        "forte":                 ["cybersecurity", "information security", "network protocols", "ethical hacking"],
        "available_days":        ["Monday", "Wednesday", "Thursday"],
        "time_slot":             ["morning"],
        "communication_preference": "face-to-face",
        "meeting_frequency":     "weekly",
        "experience":            10,
        "mentor_capacity":       3,
        "prior_mentees_count":   8,
        "self_description":      "I specialize in cybersecurity, ethical hacking, and network security research with deep expertise in cryptographic protocols and Linux-based penetration testing.",
        "prev_mentored_thesis":  [
            "Network Intrusion Detection using Machine Learning",
            "Cryptographic Protocols for IoT Security",
        ],
        "published_papers":      [
            "Penetration Testing Methodology for Web Applications",
            "Kali Linux Tools for Network Vulnerability Assessment",
        ],
        "certifications":        ["Certified Ethical Hacker (CEH)", "OSCP", "CompTIA Security+"],
        "profile_completed":     True,
    },
    {
        "id":                    "a0000000-0000-0000-0000-000000000004",
        "first_name":            "David",
        "last_name":             "Lim",
        "email":                 "david.lim@demo.edu",
        "technical_skills":      ["SQL", "PostgreSQL", "MongoDB", "Apache Spark", "data warehousing", "ETL", "data engineering"],
        "forte":                 ["database systems", "big data", "data engineering", "data analytics"],
        "available_days":        ["Tuesday", "Wednesday", "Friday"],
        "time_slot":             ["morning", "afternoon"],
        "communication_preference": "hybrid",
        "meeting_frequency":     "biweekly",
        "experience":            12,
        "mentor_capacity":       4,
        "prior_mentees_count":   10,
        "self_description":      "I have extensive experience in database systems, big data engineering, and ETL pipeline design using PostgreSQL, MongoDB, and Apache Spark.",
        "prev_mentored_thesis":  [
            "Big Data Processing for E-commerce Analytics",
            "Distributed PostgreSQL for Healthcare Records",
        ],
        "published_papers":      [
            "Apache Spark Optimization for Large-scale ETL",
            "PostgreSQL vs MongoDB: A Comparative Study in Data Warehousing",
        ],
        "certifications":        ["Oracle Database Administrator", "Databricks Certified Associate Developer"],
        "profile_completed":     True,
    },
    {
        "id":                    "a0000000-0000-0000-0000-000000000005",
        "first_name":            "Elena",
        "last_name":             "Cruz",
        "email":                 "elena.cruz@demo.edu",
        "technical_skills":      ["OpenCV", "PyTorch", "image processing", "object detection", "Python", "YOLO", "convolutional neural networks"],
        "forte":                 ["computer vision", "image recognition", "deep learning", "object detection"],
        "available_days":        ["Monday", "Wednesday", "Friday"],
        "time_slot":             ["afternoon"],
        "communication_preference": "online",
        "meeting_frequency":     "weekly",
        "experience":            7,
        "mentor_capacity":       3,
        "prior_mentees_count":   4,
        "self_description":      "My research focuses on computer vision, object detection, and image recognition using PyTorch, OpenCV, and YOLO architectures.",
        "prev_mentored_thesis":  [
            "Real-time Object Detection for Traffic Monitoring",
            "Facial Recognition using Convolutional Neural Networks",
        ],
        "published_papers":      [
            "YOLO-based Object Detection in Surveillance Systems",
            "OpenCV and PyTorch for Industrial Image Inspection",
        ],
        "certifications":        ["NVIDIA Deep Learning Institute — Computer Vision", "PyTorch Developer Certified"],
        "profile_completed":     True,
    },
    {
        "id":                    "a0000000-0000-0000-0000-000000000006",
        "first_name":            "Felix",
        "last_name":             "Tan",
        "email":                 "felix.tan@demo.edu",
        "technical_skills":      ["Flutter", "Android", "iOS", "IoT", "embedded systems", "Dart", "mobile development"],
        "forte":                 ["mobile development", "internet of things", "embedded systems", "cross-platform development"],
        "available_days":        ["Monday", "Thursday"],
        "time_slot":             ["morning", "evening"],
        "communication_preference": "face-to-face",
        "meeting_frequency":     "monthly",
        "experience":            9,
        "mentor_capacity":       4,
        "prior_mentees_count":   7,
        "self_description":      "I specialize in mobile development using Flutter and Dart for Android and iOS, with research interests in IoT systems and embedded hardware integration.",
        "prev_mentored_thesis":  [
            "Flutter-based Smart Campus Mobile Application",
            "IoT Sensor Network for Environmental Monitoring",
        ],
        "published_papers":      [
            "Cross-platform Mobile Development with Flutter and Dart",
            "Embedded Systems Design for IoT Health Monitoring",
        ],
        "certifications":        ["Google Associate Android Developer", "Flutter Certified Application Developer"],
        "profile_completed":     True,
    },
]


MOCK_MENTEES = [
    # ── Dr. Ana Reyes (ML / AI) ──────────────────────────────────────────────
    {
        "id":                       "b0000000-0000-0000-0000-000000000001",
        "group_name":               "Group Prometheus",
        "research_title":           "Predicting Student Academic Performance using Machine Learning",
        "research_description":     "This study applies machine learning algorithms — specifically scikit-learn and TensorFlow — to predict academic outcomes from historical student data. Neural networks are used for feature extraction and classification, with Python as the primary language.",
        "mentor_preference":        "machine learning, data science, artificial intelligence",
        "available_days":           ["Monday", "Wednesday"],
        "time_slot":                ["morning"],
        "communication_preference": "hybrid",
        "meeting_frequency":        "weekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000002",
        "group_name":               "Neural Architects",
        "research_title":           "Deep Learning for Medical Image Diagnosis",
        "research_description":     "Applying deep learning and neural networks using TensorFlow to classify medical images for early disease detection. The study focuses on convolutional neural networks trained on clinical datasets using Python and scikit-learn for preprocessing.",
        "mentor_preference":        "deep learning, neural networks, TensorFlow",
        "available_days":           ["Wednesday", "Friday"],
        "time_slot":                ["afternoon"],
        "communication_preference": "hybrid",
        "meeting_frequency":        "weekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000003",
        "group_name":               "Data Forge",
        "research_title":           "Sentiment Analysis using Machine Learning and Natural Language Processing",
        "research_description":     "This research uses scikit-learn and Python to build a machine learning model for sentiment classification of social media text. Artificial intelligence and data science techniques are applied for text preprocessing and model evaluation.",
        "mentor_preference":        "machine learning, Python, artificial intelligence",
        "available_days":           ["Monday", "Friday"],
        "time_slot":                ["morning", "afternoon"],
        "communication_preference": "online",
        "meeting_frequency":        "weekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000004",
        "group_name":               "Algorithm X",
        "research_title":           "Reinforcement Learning for Autonomous Decision Making",
        "research_description":     "Implementing reinforcement learning using TensorFlow and Python to train agents for autonomous decision-making in simulated environments. Deep learning and neural networks are applied for state representation and reward optimization.",
        "mentor_preference":        "reinforcement learning, deep learning, machine learning",
        "available_days":           ["Monday", "Wednesday"],
        "time_slot":                ["afternoon"],
        "communication_preference": "online",
        "meeting_frequency":        "biweekly",
    },

    # ── Prof. Ben Santos (Software Engineering / Web) ────────────────────────
    {
        "id":                       "b0000000-0000-0000-0000-000000000005",
        "group_name":               "Code Collective",
        "research_title":           "Full-stack Web Application for University Event Management using React and Node.js",
        "research_description":     "Building a full-stack web application using React for the frontend and Node.js for the backend API layer. The project follows agile software engineering methodology and applies software architecture principles including RESTful design.",
        "mentor_preference":        "web development, React, Node.js, agile",
        "available_days":           ["Tuesday", "Thursday"],
        "time_slot":                ["afternoon"],
        "communication_preference": "online",
        "meeting_frequency":        "biweekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000006",
        "group_name":               "DevStack",
        "research_title":           "Progressive Web Application for Course Scheduling using TypeScript and React",
        "research_description":     "Developing a progressive web application using TypeScript and React following agile methodology. The backend uses Node.js with software architecture patterns emphasizing full-stack development and clean code practices.",
        "mentor_preference":        "TypeScript, React, software engineering",
        "available_days":           ["Thursday", "Friday"],
        "time_slot":                ["afternoon", "evening"],
        "communication_preference": "online",
        "meeting_frequency":        "biweekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000007",
        "group_name":               "WebForge",
        "research_title":           "Software Architecture Design for a Scalable E-Commerce Platform",
        "research_description":     "Designing and implementing scalable software architecture for e-commerce using React, Node.js, and TypeScript. Agile development practices are applied throughout the full-stack development lifecycle including modular component design.",
        "mentor_preference":        "software architecture, full-stack development, agile",
        "available_days":           ["Tuesday", "Friday"],
        "time_slot":                ["evening"],
        "communication_preference": "online",
        "meeting_frequency":        "biweekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000008",
        "group_name":               "System Builders",
        "research_title":           "Agile Development of a Real-time Collaboration Tool using JavaScript",
        "research_description":     "Using agile software engineering methodology to develop a real-time collaboration platform with JavaScript, React, and Node.js. The study explores web development design patterns and software architecture for collaborative systems.",
        "mentor_preference":        "JavaScript, agile methodology, web development",
        "available_days":           ["Tuesday", "Thursday"],
        "time_slot":                ["afternoon"],
        "communication_preference": "hybrid",
        "meeting_frequency":        "weekly",
    },

    # ── Dr. Clara Mendoza (Cybersecurity) ────────────────────────────────────
    {
        "id":                       "b0000000-0000-0000-0000-000000000009",
        "group_name":               "CipherForce",
        "research_title":           "Penetration Testing Framework for Web Application Security",
        "research_description":     "Developing a penetration testing methodology for identifying vulnerabilities in web applications. Using Python, Kali Linux, and ethical hacking techniques to assess network security and information security posture of target systems.",
        "mentor_preference":        "cybersecurity, penetration testing, ethical hacking",
        "available_days":           ["Monday", "Wednesday"],
        "time_slot":                ["morning"],
        "communication_preference": "face-to-face",
        "meeting_frequency":        "weekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000010",
        "group_name":               "SecureGuard",
        "research_title":           "Cryptographic Protocol for Secure Data Transmission in Network Systems",
        "research_description":     "Designing a cryptography-based protocol for securing network communications against eavesdropping and tampering. Using Python to implement information security mechanisms and network protocols with penetration testing for validation.",
        "mentor_preference":        "cryptography, network security, information security",
        "available_days":           ["Monday", "Thursday"],
        "time_slot":                ["morning"],
        "communication_preference": "face-to-face",
        "meeting_frequency":        "weekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000011",
        "group_name":               "NetShield",
        "research_title":           "Network Intrusion Detection System using Cybersecurity and Python",
        "research_description":     "Building a network security intrusion detection system using cybersecurity techniques and Python on Linux. The system uses ethical hacking principles and network protocol analysis with Kali Linux tools to detect and classify threats.",
        "mentor_preference":        "network security, Linux, cybersecurity",
        "available_days":           ["Wednesday", "Thursday"],
        "time_slot":                ["morning"],
        "communication_preference": "face-to-face",
        "meeting_frequency":        "weekly",
    },

    # ── Prof. David Lim (Database / Big Data) ────────────────────────────────
    {
        "id":                       "b0000000-0000-0000-0000-000000000012",
        "group_name":               "DataVault",
        "research_title":           "Distributed Database System for Healthcare Records Management",
        "research_description":     "Designing a distributed database system using PostgreSQL and MongoDB for managing large-scale healthcare records. The study applies big data principles with ETL pipelines and data warehousing strategies for efficient analytics.",
        "mentor_preference":        "database systems, PostgreSQL, big data",
        "available_days":           ["Tuesday", "Wednesday"],
        "time_slot":                ["morning"],
        "communication_preference": "hybrid",
        "meeting_frequency":        "biweekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000013",
        "group_name":               "QueryPros",
        "research_title":           "Big Data Analytics Platform using Apache Spark and SQL",
        "research_description":     "Implementing a big data analytics platform using Apache Spark and SQL for processing large-scale datasets. Data engineering techniques including ETL and data warehousing are applied for business intelligence and reporting.",
        "mentor_preference":        "Apache Spark, big data, data engineering",
        "available_days":           ["Wednesday", "Friday"],
        "time_slot":                ["afternoon"],
        "communication_preference": "hybrid",
        "meeting_frequency":        "biweekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000014",
        "group_name":               "SchemaBuilders",
        "research_title":           "PostgreSQL Performance Optimization for Large-scale Data Engineering",
        "research_description":     "Investigating performance optimization strategies for PostgreSQL in data engineering workflows. The study covers SQL query tuning, indexing design, and integration with Apache Spark for big data processing and ETL pipelines.",
        "mentor_preference":        "PostgreSQL, SQL, data warehousing",
        "available_days":           ["Tuesday", "Friday"],
        "time_slot":                ["morning", "afternoon"],
        "communication_preference": "online",
        "meeting_frequency":        "biweekly",
    },

    # ── Dr. Elena Cruz (Computer Vision) ─────────────────────────────────────
    {
        "id":                       "b0000000-0000-0000-0000-000000000015",
        "group_name":               "VisionLab",
        "research_title":           "Real-time Object Detection using YOLO and PyTorch",
        "research_description":     "Implementing a real-time object detection system using YOLO and PyTorch for surveillance and traffic monitoring. Computer vision and image processing techniques are applied using OpenCV for video stream analysis and bounding box prediction.",
        "mentor_preference":        "computer vision, object detection, YOLO",
        "available_days":           ["Monday", "Wednesday"],
        "time_slot":                ["afternoon"],
        "communication_preference": "online",
        "meeting_frequency":        "weekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000016",
        "group_name":               "PixelMinds",
        "research_title":           "Facial Recognition System using Convolutional Neural Networks and OpenCV",
        "research_description":     "Developing a facial recognition system using convolutional neural networks implemented in PyTorch with OpenCV for preprocessing. Deep learning and image recognition techniques are combined for biometric identity verification.",
        "mentor_preference":        "image recognition, convolutional neural networks, OpenCV",
        "available_days":           ["Wednesday", "Friday"],
        "time_slot":                ["afternoon"],
        "communication_preference": "online",
        "meeting_frequency":        "weekly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000017",
        "group_name":               "SightTech",
        "research_title":           "Image Processing for Automated Quality Control using Computer Vision",
        "research_description":     "Applying computer vision and image processing using OpenCV and PyTorch for automated quality inspection in manufacturing. Object detection and deep learning identify defects, while image recognition validates product conformity.",
        "mentor_preference":        "image processing, computer vision, PyTorch",
        "available_days":           ["Monday", "Friday"],
        "time_slot":                ["afternoon"],
        "communication_preference": "online",
        "meeting_frequency":        "weekly",
    },

    # ── Prof. Felix Tan (Mobile / IoT) ───────────────────────────────────────
    {
        "id":                       "b0000000-0000-0000-0000-000000000018",
        "group_name":               "MobileHub",
        "research_title":           "Cross-platform Flutter Application for Smart Home IoT Control",
        "research_description":     "Building a cross-platform mobile application using Flutter and Dart for controlling IoT smart home devices on Android and iOS. The system integrates with embedded sensors and actuators for real-time smart home automation.",
        "mentor_preference":        "Flutter, mobile development, IoT",
        "available_days":           ["Monday", "Thursday"],
        "time_slot":                ["morning"],
        "communication_preference": "face-to-face",
        "meeting_frequency":        "monthly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000019",
        "group_name":               "IoTLink",
        "research_title":           "IoT-based Environmental Monitoring System with Android Mobile Dashboard",
        "research_description":     "Developing an IoT environmental monitoring system with an Android mobile dashboard built in Flutter. Embedded systems and sensors transmit sensor data to the mobile application for real-time display and alerting on both Android and iOS.",
        "mentor_preference":        "IoT, Android, embedded systems",
        "available_days":           ["Monday", "Thursday"],
        "time_slot":                ["morning", "evening"],
        "communication_preference": "face-to-face",
        "meeting_frequency":        "monthly",
    },
    {
        "id":                       "b0000000-0000-0000-0000-000000000020",
        "group_name":               "EmbedDev",
        "research_title":           "Flutter Health Monitoring App with Wearable IoT Device Integration",
        "research_description":     "Creating a Flutter mobile application for real-time health monitoring using IoT wearable devices on Android and iOS platforms. Embedded systems hardware continuously collects biometric data, which the cross-platform mobile app visualizes.",
        "mentor_preference":        "Flutter, IoT, mobile development, embedded systems",
        "available_days":           ["Thursday"],
        "time_slot":                ["evening"],
        "communication_preference": "hybrid",
        "meeting_frequency":        "monthly",
    },
]
