-- Stores each mentee's full ranked list of mentors (generated by matching algo)
create table if not exists mentee_preferences (
    mentee_group_id uuid primary key references "MENTEE_GROUPS"(id) on delete cascade,
    ranked_mentors  jsonb not null default '[]'::jsonb,
    -- each element: { rank, mentor_id, name, score, matched_keywords[] }
    created_at      timestamp with time zone default now()
);

-- Stores each mentor's full ranked list of mentee groups
create table if not exists mentor_preferences (
    mentor_id      uuid primary key references mentor(id) on delete cascade,
    ranked_mentees jsonb not null default '[]'::jsonb,
    -- each element: { rank, mentee_group_id, group_name, research_title, score, matched_keywords[] }
    created_at     timestamp with time zone default now()
);
